# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: instrument.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'instrument.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10instrument.proto\"\x07\n\x05\x45mpty\"\x0f\n\rStatusRequest\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"Z\n\x0e\x43hannelRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\x05\x12\x15\n\rvoltage_limit\x18\x02 \x01(\x02\x12\x0f\n\x07voltage\x18\x03 \x01(\x02\x12\x0f\n\x07\x63urrent\x18\x04 \x01(\x02\"3\n\x0f\x43hannelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x12\x44\x65viceListResponse\x12\x0f\n\x07\x64\x65vices\x18\x01 \x03(\t\" \n\rDeviceRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"6\n\x12\x43onnectionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\rOutputRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\x08\"2\n\x0eOutputResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\x0bReadChannel\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\x05\"E\n\x0eVoltageReading\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0f\n\x07voltage\x18\x02 \x01(\x02\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\x05\x32\xbc\x03\n\x11InstrumentService\x12,\n\tGetStatus\x12\x0e.StatusRequest\x1a\x0f.StatusResponse\x12/\n\nSetChannel\x12\x0f.ChannelRequest\x1a\x10.ChannelResponse\x12*\n\x0bListDevices\x12\x06.Empty\x1a\x13.DeviceListResponse\x12\x34\n\rConnectDevice\x12\x0e.DeviceRequest\x1a\x13.ConnectionResponse\x12/\n\x10\x44isconnectDevice\x12\x06.Empty\x1a\x13.ConnectionResponse\x12-\n\x0eInitializeVISA\x12\x06.Empty\x1a\x13.ConnectionResponse\x12,\n\tSetOutput\x12\x0e.OutputRequest\x1a\x0f.OutputResponse\x12\'\n\x0fStartMonitoring\x12\x0c.ReadChannel\x1a\x06.Empty\x12/\n\x0eMonitorVoltage\x12\x0c.ReadChannel\x1a\x0f.VoltageReadingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'instrument_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_STATUSREQUEST']._serialized_start=29
  _globals['_STATUSREQUEST']._serialized_end=44
  _globals['_STATUSRESPONSE']._serialized_start=46
  _globals['_STATUSRESPONSE']._serialized_end=78
  _globals['_CHANNELREQUEST']._serialized_start=80
  _globals['_CHANNELREQUEST']._serialized_end=170
  _globals['_CHANNELRESPONSE']._serialized_start=172
  _globals['_CHANNELRESPONSE']._serialized_end=223
  _globals['_DEVICELISTRESPONSE']._serialized_start=225
  _globals['_DEVICELISTRESPONSE']._serialized_end=262
  _globals['_DEVICEREQUEST']._serialized_start=264
  _globals['_DEVICEREQUEST']._serialized_end=296
  _globals['_CONNECTIONRESPONSE']._serialized_start=298
  _globals['_CONNECTIONRESPONSE']._serialized_end=352
  _globals['_OUTPUTREQUEST']._serialized_start=354
  _globals['_OUTPUTREQUEST']._serialized_end=401
  _globals['_OUTPUTRESPONSE']._serialized_start=403
  _globals['_OUTPUTRESPONSE']._serialized_end=453
  _globals['_READCHANNEL']._serialized_start=455
  _globals['_READCHANNEL']._serialized_end=485
  _globals['_VOLTAGEREADING']._serialized_start=487
  _globals['_VOLTAGEREADING']._serialized_end=556
  _globals['_INSTRUMENTSERVICE']._serialized_start=559
  _globals['_INSTRUMENTSERVICE']._serialized_end=1003
# @@protoc_insertion_point(module_scope)
